name = "Starlight"
uuid = "d1cf4e9a-6cca-406a-9108-c467415791d1"
authors = ["Joshua Higginbotham <jhigginbotham64@gmail.com> and contributors"]
version = "0.2.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"
Telescope = "5cda3ad9-a1fd-4c59-8c0c-bd6100725b84"
Telescope_jll = "ae456e04-aaf2-55ce-80c6-09193969412e"
alsa_plugins_jll = "5ac2f6bb-493e-5871-9171-112d4c21a6e7"

[compat]
Colors = "0.12.8"
DataFrames = "1.3.2"
DataStructures = "0.18.11"
Reexport = "1.2.2"
FileIO = "1.13.0"
OhMyREPL = "0.5.12"
Revise = "3.3.3"
SimpleDirectMediaLayer = "0.3.0"
Telescope = "0.2.0"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
