name = "Starlight"
uuid = "d1cf4e9a-6cca-406a-9108-c467415791d1"
authors = ["Joshua Higginbotham <jhigginbotham64@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PortAudio = "80ea8bcb-4634-5cb3-8ee8-a132660d1d2d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"

[compat]
Colors = "0.12.8"
DataFrames = "1.3.2"
DataStructures = "0.18.11"
DotEnv = "0.3.1"
Reexport = "1.2.2"
SimpleDirectMediaLayer = "0.3.0"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
